
import './globals.css'
import { Poppins } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import Footer from './components/footer/footer'


const poppins = Poppins({weight:["400","600"], subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App ',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        
        </body>
    </html>
  )
}
